from __future__ import annotations

from html import escape

from app.domain.models import TicketStatus


_SERVICENOW_URL = "https://ihg.service-now.com"

_HTML_WRAPPER_OPEN = (
    "<html><body style=\"margin:0;padding:0;background:#f6f8fb;\">"
    "<table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" "
    "style=\"background:#f6f8fb;padding:20px 0;\"><tr><td align=\"center\">"
    "<table role=\"presentation\" width=\"640\" cellspacing=\"0\" cellpadding=\"0\" "
    "style=\"max-width:640px;width:100%;background:#ffffff;border:1px solid #e5e7eb;border-radius:10px;\">"
    "<tr><td style=\"padding:24px 28px;font-family:Segoe UI,Arial,sans-serif;"
    "color:#1f2937;font-size:14px;line-height:1.6;\">"
)
_HTML_WRAPPER_CLOSE = "</td></tr></table></td></tr></table></body></html>"


def _html_greeting(sender_name: str) -> str:
    name = escape(sender_name.strip()) if sender_name.strip() else "Team"
    return f"<p style=\"margin:0 0 14px;\">Hi {name},</p>"


def build_no_ticket_found_reply(sender_name: str = "", servicenow_url: str = _SERVICENOW_URL) -> str:
    """UC4 Step 4: No INC/ADH ticket number found — ask sender to raise a new case."""
    safe_url = escape(servicenow_url)
    # Generated by GitHub Copilot
    return (
        _HTML_WRAPPER_OPEN
        + _html_greeting(sender_name)
        + "<p style=\"margin:0 0 14px;\">Hope you are doing well.</p>"
        + "<p style=\"margin:0 0 14px;\">We reviewed your query and found that no reference "
          "case number was mentioned in your email. To assist you further, please share the "
          "relevant case number. If you do not have one, kindly raise a new case using the "
          "following link:</p>"
        + f"<p style=\"margin:0 0 14px;\"><a href=\"{safe_url}\" "
          f"style=\"color:#2563eb;\">{safe_url}</a></p>"
        + "<p style=\"margin:0 0 14px;\">Looking forward to your response.</p>"
        + "<p style=\"margin:0;\">Thanks &amp; Regards,<br/><strong>GenWizard Automation Team</strong></p>"
        + _HTML_WRAPPER_CLOSE
    )


def build_open_ticket_reply(sender_name: str = "", servicenow_url: str = _SERVICENOW_URL) -> str:
    """UC4 Step 4: No INC/ADH ticket number found — ask sender to raise a new case."""
    safe_url = escape(servicenow_url)
    # Generated by GitHub Copilot
    return (
        _HTML_WRAPPER_OPEN
        + _html_greeting(sender_name)
        + "<p style=\"margin:0 0 14px;\">Hope you are doing well.</p>"
        + "<p style=\"margin:0 0 14px;\">We reviewed your query and found the reference "
          "case number mentioned in your email. To assist you further, please share the "
          "relevant case number. If you do not have one, kindly raise a new case using the "
          "following link:</p>"
        + f"<p style=\"margin:0 0 14px;\"><a href=\"{safe_url}\" "
          f"style=\"color:#2563eb;\">{safe_url}</a></p>"
        + "<p style=\"margin:0 0 14px;\">Looking forward to your response.</p>"
        + "<p style=\"margin:0;\">Thanks &amp; Regards,<br/><strong>GenWizard Automation Team</strong></p>"
        + _HTML_WRAPPER_CLOSE
    )


def build_general_query_reply() -> str:
    """Build an HTML acknowledgement reply for non-business queries."""
    # Generated by GitHub Copilot
    return (
        "<html><body style=\"margin:0;padding:0;background:#f6f8fb;\">"
        "<table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" "
        "style=\"background:#f6f8fb;padding:20px 0;\"><tr><td align=\"center\">"
        "<table role=\"presentation\" width=\"640\" cellspacing=\"0\" cellpadding=\"0\" "
        "style=\"max-width:640px;width:100%;background:#ffffff;border:1px solid #e5e7eb;border-radius:10px;\">"
        "<tr><td style=\"padding:24px 28px;font-family:Segoe UI,Arial,sans-serif;color:#1f2937;font-size:14px;line-height:1.6;\">"
        "<p style=\"margin:0 0 14px;\">Hello,</p>"
        "<p style=\"margin:0 0 14px;\">Thank you for reaching out.</p>"
        "<p style=\"margin:0 0 14px;\">We have received your message and shared it with the Support team.</p>"
        "<p style=\"margin:0 0 8px;font-weight:600;\">Next steps:</p>"
        "<ul style=\"margin:0 0 14px 20px;padding:0;\">"
        "<li style=\"margin:0 0 6px;\">Our Support Engineers are copied on this email</li>"
        "<li style=\"margin:0 0 6px;\">The team will review your request and respond as soon as possible</li>"
        "</ul>"
        "<p style=\"margin:0;\">Best regards,<br/>Support Team</p>"
        "</td></tr></table></td></tr></table></body></html>"
    )


def build_reviewing_ticket_reply(
    ticket_number: str,
    status: TicketStatus,
    sender_name: str = "",
) -> str:
    safe_ticket = escape(ticket_number)
    safe_status = escape(status.value.capitalize())
    return (
        _HTML_WRAPPER_OPEN
        + _html_greeting(sender_name)
        + f"<p style=\"margin:0 0 14px;\">We are reviewing your query, and your incident is currently {safe_status}.</p>"
        + "<p style=\"margin:0 0 14px;\">Your query will be automatically added to this incident.</p>"
        + "<p style=\"margin:0 0 14px;\">Our support team has been notified and will take further action on the below:</p>"
        + f"<p style=\"margin:0 0 14px;\"><strong>Incident Number:</strong> {safe_ticket}<br/>"
        + "<p style=\"margin:0;\">Best Regards,<br/><strong>GenWizard Automation Team</strong></p>"
        + _HTML_WRAPPER_CLOSE
    )

def build_add_comment_ticket_reply(
    ticket_number: str,
    sender_name: str = "",
    servicenow_url: str = _SERVICENOW_URL,
) -> str:
    safe_ticket = escape(ticket_number)
    safe_url = escape(servicenow_url)
    return (
        _HTML_WRAPPER_OPEN
        + _html_greeting(sender_name)
        + f"<p style=\"margin:0 0 14px;\">We have added your query to the ticket : </strong> {safe_ticket}<br/></p>"
        + "<p style=\"margin:0 0 14px;\">And it has been forwarded to the Support Team for timely assistance.<br/></p>"
        + "<p style=\"margin:0 0 14px;\">You will also receive email communication from IHG Service Desk "
          f"link: <a href=\"{safe_url}\" style=\"color:#2563eb;\">{safe_url}</a></p>"
        + "<p style=\"margin:0 0 14px;\">regarding this request. <br/></p>"
        + "<p style=\"margin:0 0 14px;\">In case you have any further queries or additional information to share, </p>"
        + "<p style=\"margin:0 0 14px;\">please feel free to reply directly to that email.<br/></p>"
        + "<p style=\"margin:0;\">Thanks & Regards,<br/><strong>GenWizard Automation Team</strong></p>"
        + _HTML_WRAPPER_CLOSE
    )


def build_closed_ticket_reply(
    ticket_number: str,
    status: TicketStatus,
    sender_name: str = "",
    servicenow_url: str = _SERVICENOW_URL,
) -> str:
    """UC4 Step 5: Terminal ticket state — ask sender to provide/open an active case."""
    safe_status = escape(status.value.capitalize())
    safe_url = escape(servicenow_url)
    safe_ticket = escape(ticket_number)
    # Generated by GitHub Copilot
    return (
        _HTML_WRAPPER_OPEN
        + _html_greeting(sender_name)
        + "<p style=\"margin:0 0 14px;\">Hope you're doing well!</p>"
        + "<p style=\"margin:0 0 14px;\">We have received your query and reviewed the "
          "mentioned case number {safe_ticket}. It appears that the case is currently in a "
          f"<strong>{safe_status}</strong> state.</p>"
        + "<p style=\"margin:0 0 14px;\">To assist you further, please share an open case "
          "number. If you do not have one, kindly raise a new case using the following "
          f"link: <a href=\"{safe_url}\" style=\"color:#2563eb;\">{safe_url}</a></p>"
        + "<p style=\"margin:0 0 14px;\">Looking forward to your response.</p>"
        + "<p style=\"margin:0;\">Best Regards,<br/><strong>GenWizard Automation Team</strong></p>"
        + _HTML_WRAPPER_CLOSE
    )
